In [ ]:
  #Sckit Learn

In [ ]:
#1
from sklearn.datasets import load_iris

In [ ]:
iris=load_iris()

In [ ]:
X=iris.data
Y=iris.target

In [ ]:
feature_names=iris.feature_names
target_names=iris.target_names

In [ ]:
print("Feature Names:",feature_names)
print("Target Names:",target_names)
print("\nFirst 10 rows X:\n",X[:10])

Feature Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target Names: ['setosa' 'versicolor' 'virginica']

First 10 rows X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [ ]:
#2
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_test,y_train = train_test_split(X,Y,test_size=0.3,random_state=1)

In [ ]:
print(X_train.shape)

(105, 4)


In [ ]:
print(X_test.shape)

(45, 4)


In [ ]:
print(y_train.shape)

(45,)


(105,)


In [ ]:
#3
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.4, random_state=1)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from sklearn import metrics

In [ ]:
classifier_knn=KNeighborsClassifier(n_neighbors=3)

In [ ]:
classifier_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred=classifier_knn.predict(X_test)

In [ ]:
# Finding accuracy by comparing actual response values(y_test)with predicted response value(y_pred)

In [ ]:
print("Accuracy",metrics.accuracy_score(y_test,y_pred))

Accuracy 0.9833333333333333


In [ ]:
sample=[[5,5,3,2],[2,4,3,5]]
preds=classifier_knn.predict(sample)

In [ ]:
pred_species=[iris.target_names[p] for p in preds]
print("Predictions",pred_species)

Predictions ['versicolor', 'virginica']


In [ ]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
# from sklearn.externals import joblib

In [ ]:
####################

In [ ]:
import numpy as np

In [ ]:
from sklearn import preprocessing

In [ ]:
Input_data=np.array([[2.1,-1.9,5.5],[-1.5,2.4,3.5],[0.5,-7.9,5.6],[5.9,2.3,-5.8]])

In [ ]:
#displaying the mean and the standard deviation of the input data

In [ ]:
print("Mean =",Input_data.mean(axis=0))

Mean = [ 1.75  -1.275  2.2  ]


In [ ]:
print("Stddeviation = ",Input_data.std(axis=0))

Stddeviation =  [2.71431391 4.20022321 4.69414529]


In [ ]:
#removing the mean and the standard deviation of the input data

In [ ]:
data_scaled=preprocessing.scale(Input_data)

In [ ]:
print("Mean removed ",data_scaled.mean(axis=0))

Mean removed  [1.11022302e-16 0.00000000e+00 0.00000000e+00]


In [ ]:
print("STDdeviation",data_scaled.std(axis=0))

STDdeviation [1. 1. 1.]


In [ ]:
# data_scaler_minmax=